#!/usr/bin/env bash

# autostart script by all x11 window managers (the only one i currently use is i3) on my system
polybar example &
picom --experimental-backends -b &
~/wallpapers/wallpaper.sh &
dunst &
blueman-applet &

